version: '2'

services:
  web:
    build: ./docker/
    ports: ["80:80"]
    depends_on: [redis,es,db]
    volumes:
      - .:/var/www/html
  redis:
    image: redis:alpine
  es:
    image: elasticsearch:5-alpine
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports: ["9200:9200"]
  db:
    image: mvertes/alpine-mongo
    command: mongod --smallfiles
    volumes:
      - dbdata:/data/db
volumes:
  esdata:
  dbdata: