version: '2'

services:
  web:
    build: docker
    depends_on:
      - hub
      - firefox

  hub:
    image: atanistra/selenium-hub
    ports:
      - '4444:4444'

  firefox:
    image: atanistra/selenium-node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - hub
    tmpfs:
      - /tmp
